---
- name: Update packages
  become: yes
  apt:
    update_cache: yes

- name: Install apache2
  become: yes
  apt:
    name: apache2
    state: present

- name: Copy index.html
  copy:
    src: index.html
    dst: /var/www/html/index.html